Add more devstack configuration to networking-cisco job

diff --git a/jenkins/jobs/networking-cisco.yaml b/jenkins/jobs/networking-cisco.yaml
--- a/jenkins/jobs/networking-cisco.yaml
+++ b/jenkins/jobs/networking-cisco.yaml
@@ -20,7 +20,25 @@
 
           #export DEVSTACK_GATE_TOPOLOGY="multinode"
 
+          export OVERRIDE_ZUUL_BRANCH=stable/ocata
+
           function pre_test_hook {{
+            if is_suse || is_fedora; then
+              local ovs_package='openvswitch'
+              local ovs_service='openvswitch'
+            elif uses_debs; then
+              local ovs_package='openvswitch-switch'
+              local ovs_service='openvswitch-switch'
+            else
+              echo "Unsupported platform, can't determine openvswitch service"
+              exit 1
+            fi
+
+            local install_ovs_deps="source $BASE/new/devstack/functions-common; \
+                                    install_package ${ovs_package}; \
+                                    restart_service ${ovs_service}"
+            eval $install_ovs_deps
+
             # Setup the virtual L2 path to the nexus
             local private_ip=$(cat /etc/nodepool/primary_node_private)
             local tapid=$(cat /etc/nodepool/uuid | cut -c1-8)
@@ -34,9 +52,13 @@
             sudo ip link add nexustap1 type gretap local $private_ip remote 10.0.0.15 key 1
             sudo ip link add nexustap2 type gretap local $private_ip remote 10.0.0.15 key 2
 
+            sudo ovs-vsctl add-br br-nexusnet
+            sudo ovs-vsctl add-br br-ex
+
+            sudo ovs-vsctl add-port br-nexusnet nexustap1
+
             # Claim a vlan range from the CI system 
             export CLAIMED_VLAN_RANGE=$(python /opt/nodepool-scripts/claim_vlan.py)
-            export DEVSTACK_LOCAL_CONFIG+=$'\n'"TENANT_VLAN_RANGE=${{vlan_range}}"
           }}
           export -f pre_test_hook
 
@@ -62,6 +84,10 @@
           export PROJECTS="openstack/networking-cisco $PROJECTS"
 
           export DEVSTACK_LOCAL_CONFIG+=$'\n'"enable_plugin networking-cisco https://git.openstack.org/openstack/networking-cisco"
+          export DEVSTACK_LOCAL_CONFIG+=$'\n'"ML2_VLAN_RANGES=nexusnet:${{CLAIMED_VLAN_RANGE}}"
+          export DEVSTACK_LOCAL_CONFIG+=$'\n'"OVS_VLAN_RANGES=nexusnet:${{CLAIMED_VLAN_RANGE}}"
+          export DEVSTACK_LOCAL_CONFIG+=$'\n'"ENABLE_TENANT_VLANS=True"
+          export DEVSTACK_LOCAL_CONFIG+=$'\n'"OVS_BRDIGE_MAPPINGS=public:br-ex,nexusnet:br-nexusnet"
 
           cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
           ./safe-devstack-vm-gate-wrap.sh
